quay.io/coreos/flannel:v0.10.0-amd64
quay.io/coreos/flannel:v0.10.0-arm64
quay.io/coreos/flannel:v0.10.0-arm
quay.io/coreos/flannel:v0.10.0-ppc64le
quay.io/coreos/flannel:v0.10.0-s390x
MAINTAINER chen13626@126.com